Switch for R-calculations and path for shapefiles for Ronald
I needed to add the switch to skip the R calculations since I had problems on my computer:
--
 .onLoad failed in loadNamespace() for 'units', details:
  call: ud_init(path)
  error: no database found!
--
Second I had to adjust several path values to run for the different locations on my computer.
This was done in the 'setup-gis' procedure.